version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend-network

  backend:
    image: omarkhedimallah/backend-audit:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pi?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - DB_HOST=mysql
      - DB_NAME=pi
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8083:8083"
    expose:
      - 8083
    depends_on:
      - mysql
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
