# Exported from Render on 2024-06-29T15:24:59Z
services:
- type: web
  name: Render
  runtime: docker
  repo: https://github.com/khalilkhemiri/Render
  plan: free
  region: oregon
  dockerCommand: mvn clean package
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
